### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by nesl247** [dracula/sequel-pro#1]
Hey everyone,

We're looking for a maintainer for Sequel Pro. Dracula theme has grown significantly and it's too much for one person. If you are interested in becoming the maintainer, please reply here.

We're not going to let issues and pull requests get behind though just because we don't have a dedicated maintainer, so fear not.

Thanks.
- Dracula Theme Team

**Comment by zenorocha** [comment]
I believe that @florianeckerstorfer (the creator of this theme) should be the maintainer ;)

**Comment by nesl247** [comment]
@florianeckerstorfer Since you created the theme, would you like to be the maintainer? If so I'll add you right away.

Thanks!

**Comment by florianeckerstorfer** [comment]
Yes, I can maintain the theme if you want to.

**Comment by nesl247** [comment]
I've sent you an invite. Thanks!
